package com.chrosciu.rxbattleships.service;

import com.chrosciu.rxbattleships.model.Field;
import reactor.core.publisher.Flux;

/**
 * Service wrapping Field events generated by BoardMouseAdapter to reactive stream
 */
public interface FieldFluxService {
    /**
     * Get Flux object that signals each field click
     * reported by listener registered in BoardMouseAdapter
     * @return Flux described above
     */
    Flux<Field> getFieldFlux();
}
