package com.chrosciu.rxbattleships.service;

import com.chrosciu.rxbattleships.model.Shot;
import reactor.core.publisher.Flux;

/**
 * Service wrapping Shot events generated by BoardMouseAdapter to reactive stream
 */
public interface ShotFluxService {
    /**
     * Get Flux object that signals each Shot reported by listener registered in BoardMouseAdapter
     * @return Flux described above
     */
    Flux<Shot> getShotFlux();
}
